#!/bin/sh
#
# Copyright (C) 2017 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT init scripts.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

. /etc/helpers/linuxrc-config

mount_all
hook_get
hook_load
hook_parse_args
hook_run
hook_post

# mount root
mount -r $root /mnt

hook_deinit

umount_all

# mount helper filesystems
mount -t devtmpfs none /mnt/dev
mount -t proc none /mnt/proc
mount -t sysfs none /mnt/sys
exec switch_root /mnt /sbin/init $(/bin/cat /proc/cmdline)

# switch_root failed, failsafe mode
mount_all
# go interactive mode
set_verbosity 1
exec /bin/sh
