#!/bin/bash
#
# Copyright (C) 2017 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT init scripts.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# $1 = initramfs root, $2 - parameters (optional)
common_hook_install_fbsplash() {
	local basedir=$1

	mkdir -p "${basedir}/etc"

	if [ $(uname -m) = "x86_64" ] ; then
		mkdir -p "${basedir}/lib64"
		mkdir -p "${basedir}/usr/lib64"
		make_symlink "lib64" "${basedir}/lib"
		make_symlink "lib64" "${basedir}/usr/lib"
	else
		mkdir -p "${basedir}/lib"
		mkdir -p "${basedir}/usr/lib"
	fi

	mkdir -p "${basedir}/lib/splash/cache"

	copy_executable "${sharedir}/helpers/splash_ctl" "${basedir}/sbin/splash_ctl" "${basedir}"
	copy_executable "${sharedir}/hooks/fbsplash" "${basedir}/etc/hooks/fbsplash" "${basedir}"

	local themefile=/etc/dt-init-scripts/splash-theme.conf
	if [ -f $themefile ] ; then
		local themename="$(cat $themefile)"
		if [ -d "/etc/splash/$themename" ] ; then
			mkdir -p "${basedir}/etc/splash"
			copy "/etc/splash/$themename" "${basedir}/etc/splash/$themename" "${basedir}"
		fi
	fi
}

# $1 = initramfs root, $2 - parameters (optional)
hook_install_fbsplash() {
	local basedir=$1
	local params=$2

	common_hook_install_fbsplash $basedir $params
}

# $1 = initramfs root, $2 - parameters (optional)
hook_shutdown_install_fbsplash() {
	local basedir=$1
	local params=$2

	common_hook_install_fbsplash $basedir $params
}
