#!/bin/bash
#
# Copyright (C) 2017-2020 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT init scripts.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# $1 = initramfs root, $2 - parameters (optional)
common_hook_install_fbsplash() {
	local basedir=$1

	mkdir -p "${basedir}/etc"

	for libdir in /lib* /usr/lib* ; do
		if [[ "$libdir" != */libexec ]] ; then
			if [ -L "$libdir" ] ; then
				make_symlink "$(readlink "$libdir")" "${basedir}/${libdir}"
			else
				mkdir -p "${basedir}/${libdir}"
			fi
		fi
	done

	mkdir -p "${basedir}/lib/splash/cache"

	copy_executable "${sharedir}/helpers/splash_ctl" "${basedir}/sbin/splash_ctl" "${basedir}"
	copy_executable "${sharedir}/hooks/fbsplash" "${basedir}/etc/hooks/fbsplash" "${basedir}"
}

# $1 = initramfs root, $2 - parameters (optional)
hook_install_fbsplash() {
	local basedir=$1
	local params=$2

	common_hook_install_fbsplash $basedir $params
}

# $1 = initramfs root, $2 - parameters (optional)
hook_shutdown_install_fbsplash() {
	local basedir=$1
	local params=$2

	common_hook_install_fbsplash $basedir $params
}
