#!/bin/bash
#
# Copyright (C) 2023 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT init scripts.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

# options:
# configfile=$path
#	path to file containing description of kernel modules, each line is in format "module_name"
#	required parameter

# $1 = parameters (optional)
hook_check_params_module() {
	local params=$1
	local configfile=

	for param in $(echo $params | sed -e 's|:| |g') ; do
		case $param in
			configfile=*)
				configfile=${param#configfile=}
				;;
			# TODO: Notify about unsupported option?
		esac
	done

	[ -f "${configfile}" ] || die "Hook \"module\": configfile option doesn't point to existing file!"
}

hook_shutdown_check_params_module() {
	local params=$1
	local configfile=

	for param in $(echo $params | sed -e 's|:| |g') ; do
		case $param in
			configfile=*)
				configfile=${param#configfile=}
				;;
			# TODO: Notify about unsupported option?
		esac
	done

	[ -f "${configfile}" ] || die "Hook \"module\": configfile option doesn't point to existing file!"
}

# $1 = initramfs root, $2 - parameters (optional)
common_hook_install_module() {
	local basedir=$1
	local params=$2
	local configfile=

	for param in $(echo $params | sed -e 's|:| |g') ; do
		case $param in
			configfile=*)
				configfile=${param#configfile=}
				;;
		esac
	done

	mkdir -p "${basedir}/etc/hooks"

	copy_executable "${sharedir}/hooks/module" "${basedir}/etc/hooks/module" "${basedir}"

	copy "${configfile}" "${basedir}/${configfile}" "${basedir}"
}

# $1 = initramfs root, $2 - parameters (optional)
hook_install_module() {
	local basedir=$1
	local params=$2

	common_hook_install_module $basedir $params
}

# $1 = initramfs root, $2 - parameters (optional)
hook_shutdown_install_luks() {
	local basedir=$1
	local params=$2

	common_hook_install_module $basedir $params
}
