#!/bin/bash
#
# Copyright (C) 2017 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT init scripts.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

configdir="/etc/dt-init-scripts"
libexecdir="/usr/libexec/dt-init-scripts"
bootdir="/boot"

. "${libexecdir}/functions/common"

compression=

while read -r line ; do
	if [ ! -z "$line" ] ; then
		case $line in
			compression=\"*\")
				compression="$(echo $line | sed -e 's|^compression="||' -e 's|\"$||')"
				;;
		esac
	fi
done < "${configdir}/dt-init-scripts.conf"

if [ -f "${configdir}/splash-res.conf" -a -f "${configdir}/splash-theme.conf" ] ; then
	TMPFILE=$(mktemp)
	TMPFILE2=$(mktemp)

	BOOTFILE=initramfs-bootsplash-$(cat "${configdir}/splash-theme.conf")
	splash_geninitramfs --res=$(cat "${configdir}/splash-res.conf") -g "${TMPFILE}" $(cat "${configdir}/splash-theme.conf") -v

	gunzip < "${TMPFILE}" > "${TMPFILE2}"
	rm "${TMPFILE}"

	compress_file "${TMPFILE2}" "${bootdir}/${BOOTFILE}" "$compression"

	ln -svf ${BOOTFILE} "${bootdir}/initramfs"
fi
