#!/bin/bash
#
# Copyright (C) 2017 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT init scripts.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

configdir="/etc/dt-init-scripts"
sharedir="/usr/share/dt-init-scripts"
libexecdir="/usr/libexec/dt-init-scripts"
bootdir="/boot"

. "${libexecdir}/functions/common"

helper_copy_verbose=1

TMPDIR=$(mktemp -d)
TMPFILE=$(mktemp)
TMPFILE2=$(mktemp)

hooks=
compression=

while read -r line ; do
	if [ ! -z "$line" ] ; then
		case $line in
			initrd_hooks=\"*\")
				hooks="$(echo $line | sed -e 's|^initrd_hooks="||' -e 's|\"$||')"
				;;
			compression=\"*\")
				compression="$(echo $line | sed -e 's|^compression="||' -e 's|\"$||')"
				;;
		esac
	fi
done < "${configdir}/dt-init-scripts.conf"

# first check options and ensure required functions are provided
for hook in $(echo $hooks | sed -e 's|,| |g') ; do
	basehook="$(echo $hook | cut -d: -f 1)"
	hookopts="$(echo $hook | cut -d: -f 2- -s)"

	[ -e "${libexecdir}/modules/${basehook}" ] || die "hook \"${basehook}\" doesn't exist"

	. "${libexecdir}/modules/${basehook}"

	type -t hook_install_${basehook} >/dev/null || die "hook \"${basehook}\" doesn't provide required function \"hook_install_${basehook}\""

	if type -t hook_check_params_${basehook} >/dev/null ; then
		hook_check_params_${basehook} "${hookopts}"
	fi
done

# then install hook
for hook in $(echo $hooks | sed -e 's|,| |g') ; do
	basehook="$(echo $hook | cut -d: -f 1)"
	hookopts="$(echo $hook | cut -d: -f 2- -s)"

	hook_install_${basehook} "${TMPDIR}" "${hookopts}"
done

# and now write options
hookoptsline=

for hook in $(echo $hooks | sed -e 's|,| |g') ; do
	basehook="$(echo $hook | cut -d: -f 1)"
	hookopts="$(echo $hook | cut -d: -f 2- -s)"

	if type -t hook_write_params_${basehook} >/dev/null ; then
		hookopts="$(hook_write_params_${basehook} "${hookopts}")"
	fi

	hookoptslinepart="${basehook}"

	if [ -n "${hookopts}" ] ; then
		hookoptslinepart="${basehook}:${hookopts}"
	fi

	if [ -n "${hookoptsline}" ] ; then
		hookoptsline="${hookoptsline},${hookoptslinepart}"
	else
		hookoptsline="${hookoptslinepart}"
	fi
done

mkdir -p ${TMPDIR}/etc
echo initrd_hooks=\"${hookoptsline}\" > "${TMPDIR}/${configdir}/dt-init-scripts.conf"

cd ${TMPDIR}
find . -print | cpio -o -H newc | gzip -9 > ${TMPFILE}
chmod 644 ${TMPFILE}

if [ -f "${configdir}/splash-res.conf" -a -f "${configdir}/splash-theme.conf" ] ; then
	splash_geninitramfs --verbose --res $(cat "${configdir}/splash-res.conf") --append ${TMPFILE} $(cat "${configdir}/splash-theme.conf")
	BOOTFILE=initramfs-bootsplash-$(cat "${configdir}/splash-theme.conf")
else
	BOOTFILE=initramfs-nobootsplash
fi

gunzip < "${TMPFILE}" > "${TMPFILE2}"
rm "${TMPFILE}"

compress_file "${TMPFILE2}" "${bootdir}/${BOOTFILE}" "$compression"

ln -svf ${BOOTFILE} "${bootdir}/initramfs"

rm -rf ${TMPDIR}
