#!/bin/sh

# default options
gv_splash_silent=0
gv_active_splashutil=0
#gv_splash_theme=
#gv_splash_console=
recovery_mode=0
resume_mode=1
#root=

# some useful functions

#splash_command() {
#	local lv_cmd="$1"
#	echo "$lv_cmd"
#	[ $gv_active_splashutil ] && echo "$lv_cmd"
#	#[ $gv_active_splashutil ] && echo "$lv_cmd" > /lib/splash/cache/.splash
#}

splash_verbose() {
	[ $gv_active_splashutil = 1 ] && [ $gv_splash_silent = 1 ] && /sbin/splash_ctl verbose
#	splash_command "set mode verbose"
}

splash_silent() {
	[ $gv_active_splashutil = 1 ] && [ $gv_splash_silent = 1 ] && /sbin/splash_ctl silent
#	splash_command "set mode silent"
}

#splash_message() {
#	local lv_msg="$1"
#	splash_command "set message $lv_msg"
#	splash_command "repaint"
#}

splash_setup() {
	#[ -n "$gv_splash_console" ] && exec < "$gv_splash_console" > "$gv_splash_console" 2>&1
	#[ -e /lib/splash/cache/.splash ] || mknod /lib/splash/cache/.splash p
	#/usr/sbin/splash_util -d -t $gv_splash_theme
	gv_active_splashutil=1
}

splash_daemon_stop() {
	#[ $gv_active_splashutil ] || splash_command "exit";
	gv_active_splashutil=0
}

mount_all() {
	mount -t proc none /proc
	mount -t sysfs none /sys
	mount -t devtmpfs none /dev
}

umount_all() {
	umount /proc
	umount /sys
	umount /dev
}

getdevnumber() {
	set -- $(ls -lL $1)
	echo ${5%,}:$6
}

# parse options
parsecmdline() {
	CMDLINE=`/bin/cat /proc/cmdline`

	for cmd in $CMDLINE; do
		case $cmd in
			splash=*)
				gv_splash_theme="`echo "$cmd"|sed 's/.*theme://'|sed 's/,.*//'`"
				[ -n "`echo "$cmd"|grep silent`" ] && gv_splash_silent=1 ;;
#			CONSOLE=*)
#				gv_splash_console="`echo "$cmd"|cut -b9-`" ;;
			dtrecovery)
				recovery_mode=1 ;;
			noresume)
				resume_mode=0 ;;
			crypt_resume=*)
				resume_dev=${cmd#crypt_resume=} ;;
			root=*)
				root=${cmd#root=} ;;
		esac
	done
}
