#!/bin/sh

MTAB=$1

let mtab_items_count=0

if [ ! -z "$MTAB" ]; then
	while read -r line ; do
		set -- $(echo $line | sed -e 's:#.*$::')

		if [ ! -z "$1" ] && [ ! -z "$2" ] && [ ! -z "$3" ] && [ -z "$4" ] ; then
			eval mtab_devices${mtab_items_count}="$1"
			eval mtab_names${mtab_items_count}="$2"
			eval mtab_key_files${mtab_items_count}="$3"
			mtab_items_count=$(expr ${mtab_items_count} + 1)
		fi
	done < $MTAB
fi
