#!/bin/sh

#. /bin/linuxrc-config

#parsecmdline

. /bin/linuxrc-readmtab /etc/dt-tools/mtab.conf

filenames_encrypted=""

for i in $(seq 0 $(expr ${mtab_items_count} - 1)) ; do
	filenames_encrypted="${filenames_encrypted} /root/$(eval echo \$mtab_key_files$i).gpg"
done

# decrypt
/usr/bin/gpg --quiet --decrypt-files ${filenames_encrypted} 2>/dev/null

decrypted_everything=true

for i in $(seq 0 $(expr ${mtab_items_count} - 1)) ; do
	if [ ! -e "/root/$(eval echo \$mtab_key_files$i)" ] ; then
		decrypted_everything=false
	fi
done

if [ "$decrypted_everything" = true ] ; then
	for i in $(seq 0 $(expr ${mtab_items_count} - 1)) ; do
		/bin/cryptsetup -y --key-file "/root/$(eval echo \$mtab_key_files$i)" luksOpen "$(eval echo \$mtab_devices$i)" "$(eval echo \$mtab_names$i)"
	done
fi

for i in $(seq 0 $(expr ${mtab_items_count} - 1)) ; do
	if [ -e "/root/$(eval echo \$mtab_key_files$i)" ] ; then

		if [ -x /usr/bin/shred ] ; then
			/usr/bin/shred -u "/root/$(eval echo \$mtab_key_files$i)"
		else
			/bin/rm -f "/root/$(eval echo \$mtab_key_files$i)"
		fi
	fi
done
