#!/bin/sh
#
# Copyright (C) 2017-2020 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT init scripts.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

configdir="/etc/dt-init-scripts"
sharedir="/usr/share/dt-init-scripts"
libexecdir="/usr/libexec/dt-init-scripts"

. "${libexecdir}/functions/common"

hooks=

while read -r line ; do
	if [ ! -z "$line" ] ; then
		case $line in
			shutdown_hooks=\"*\")
				hooks="$(echo $line | sed -e 's|^shutdown_hooks="||' -e 's|\"$||')"
				;;
		esac
	fi
done < "${configdir}/dt-init-scripts.conf"

mkdir /run/dt-init-scripts-shutdown
mount -t tmpfs none /run/dt-init-scripts-shutdown

# first check options and ensure required functions are provided
for hook in $(echo $hooks | sed -e 's|,| |g') ; do
	basehook="$(echo $hook | cut -d: -f 1)"
	hookopts="$(echo $hook | cut -d: -f 2- -s)"

	[ -e "${libexecdir}/modules/${basehook}" ] || die "hook \"${basehook}\" doesn't exist"

	. "${libexecdir}/modules/${basehook}"

	type -t hook_shutdown_install_${basehook} >/dev/null || die "hook \"${basehook}\" doesn't provide required function \"hook_shutdown_install_${basehook}\""

	if type -t hook_shutdown_check_params_${basehook} >/dev/null ; then
		hook_shutdown_check_params_${basehook} "${hookopts}"
	fi
done

# then install shutdown hook
for hook in $(echo $hooks | sed -e 's|,| |g') ; do
	basehook="$(echo $hook | cut -d: -f 1)"
	hookopts="$(echo $hook | cut -d: -f 2- -s)"

	hook_shutdown_install_${basehook} "/run/dt-init-scripts-shutdown" "${hookopts}"
done

# and now write options
hookoptsline=

for hook in $(echo $hooks | sed -e 's|,| |g') ; do
	basehook="$(echo $hook | cut -d: -f 1)"
	hookopts="$(echo $hook | cut -d: -f 2- -s)"

	if type -t hook_write_params_${basehook} >/dev/null ; then
		hookopts="$(hook_write_params_${basehook} "${hookopts}")"
	fi

	hookoptslinepart="${basehook}"

	if [ -n "${hookopts}" ] ; then
		hookoptslinepart="${basehook}:${hookopts}"
	fi

	if [ -n "${hookoptsline}" ] ; then
		hookoptsline="${hookoptsline},${hookoptslinepart}"
	else
		hookoptsline="${hookoptslinepart}"
	fi
done

echo shutdown_hooks=\"${hookoptsline}\" > "/run/dt-init-scripts-shutdown/${configdir}/dt-init-scripts.conf"

mount --rbind /dev /run/dt-init-scripts-shutdown/dev
mount --rbind /sys /run/dt-init-scripts-shutdown/sys
mount --rbind /proc /run/dt-init-scripts-shutdown/proc

cd /run/dt-init-scripts-shutdown
pivot_root . oldroot
exec chroot . /bin/shutdown-newroot-run $@ </dev/console >/dev/console 2>&1
exec /bin/sh </dev/console >/dev/console 2>&1
