#!/bin/sh

cat /proc/self/mounts > /etc/mtab
umount -l /oldroot
cat /proc/self/mounts > /etc/mtab

. /bin/linuxrc-readmtab /etc/dt-tools/mtab.conf

for i in $(seq 0 $(expr ${mtab_items_count} - 1)) ; do
	/bin/cryptsetup luksClose "$(eval echo \$mtab_names$i)"
done

# shutdown or reboot here
$@

# fallback
exec /bin/sh
