#!/bin/sh
#
# Copyright (C) 2022 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT init scripts.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

helper_dm_read_mtab() {
	local MTAB=$1

	let dm_mtab_items_count=0

	if [ ! -z "$MTAB" ]; then
		while read -r line ; do
			set -- $(echo $line | sed -e 's:#.*$::')

			if [ ! -z "$1" ] && [ ! -z "$2" ] && [ -z "$3" ] ; then
				eval dm_mtab_devices_${dm_mtab_items_count}="$1"
				eval dm_mtab_names_${dm_mtab_items_count}="$2"
				dm_mtab_items_count=$(expr ${dm_mtab_items_count} + 1)
			fi
		done < $MTAB
	fi
}

# parameters: $1 - hook-specific options
hook_parse_args_dm() {
	local params=$1

	for param in $(echo $params | sed -e 's|:| |g') ; do
		case $param in
			configfile=*)
				dm_config_file=${param#configfile=}
				;;
			# TODO: Notify about unsupported option?
		esac
	done
}

hook_run_dm() {
	helper_dm_read_mtab "${dm_config_file}"

	local device_name=""

	for i in $(seq 0 $(expr ${dm_mtab_items_count} - 1)) ; do
		device_name="$(findfs "$(eval echo \$dm_mtab_devices_$i)" 2>/dev/null)"
		if [ -n "${device_name}" ] ; then
			/sbin/integritysetup open "${device_name}" "$(eval echo \$dm_mtab_names_$i)"
		fi
	done

	return 0
}

hook_shutdown_dm() {
	helper_dm_read_mtab "${dm_config_file}"

	for i in $(seq 0 $(expr ${dm_mtab_items_count} - 1)) ; do
		/sbin/integritysetup close "$(eval echo \$dm_mtab_names_$i)"
	done
}

dm_config_file=
