#!/bin/sh
#
# Copyright (C) 2017 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT init scripts.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

hook_parse_args_fbsplash() {
	local CMDLINE=$(/bin/cat /proc/cmdline)

	for cmd in $CMDLINE; do
		case $cmd in
			splash=*)
				fbsplash_theme="$(echo "$cmd"|sed 's/.*theme://'|sed 's/,.*//')"
				[ -n "$(echo "$cmd"|grep silent)" ] && fbsplash_silent=1
				;;
#			CONSOLE=*)
#				fbsplash_console="$(echo "$cmd"|cut -b9-)" ;;
		esac
	done
}

hook_set_verbosity_fbsplash() {
	local verbose=$1

	if [ $fbsplash_silent -eq 1 ] ; then
		if [ $verbose -eq 0 ] ; then
			/sbin/splash_ctl silent
		else
			/sbin/splash_ctl verbose
		fi
	fi
}

fbsplash_silent=0
fbsplash_theme=
#fbsplash_console=
