#!/bin/sh
#
# Copyright (C) 2017-2023 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT init scripts.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

helper_luks_decrypted_read_mtab() {
	local MTAB=$1

	let luks_decrypted_mtab_items_count=0

	if [ ! -z "$MTAB" ]; then
		while read -r line ; do
			set -- $(echo $line | sed -e 's:#.*$::')

			if [ ! -z "$1" ] && [ ! -z "$2" ] && [ ! -z "$3" ] && [ -z "$4" ] ; then
				eval luks_decrypted_mtab_devices_${luks_decrypted_mtab_items_count}="$1"
				eval luks_decrypted_mtab_names_${luks_decrypted_mtab_items_count}="$2"
				eval luks_decrypted_mtab_key_files_${luks_decrypted_mtab_items_count}="$3"
				luks_decrypted_mtab_items_count=$(expr ${luks_decrypted_mtab_items_count} + 1)
			fi
		done < $MTAB
	fi
}

# parameters: $1 - hook-specific options
hook_parse_args_luks_decrypted() {
	local params=$1

	for param in $(echo $params | sed -e 's|:| |g') ; do
		case $param in
			configfile=*)
				luks_decrypted_config_file=${param#configfile=}
				;;
			# TODO: Notify about unsupported option?
		esac
	done
}

hook_run_luks_decrypted() {
	helper_luks_decrypted_read_mtab "${luks_decrypted_config_file}"

	local device_name=""

	for i in $(seq 0 $(expr ${luks_decrypted_mtab_items_count} - 1)) ; do
		if [ ! -e "/root/$(eval echo \$luks_decrypted_mtab_key_files_$i)" ] ; then
			return 1
		fi
	done

	for i in $(seq 0 $(expr ${luks_decrypted_mtab_items_count} - 1)) ; do
		device_name="$(findfs "$(eval echo \$luks_decrypted_mtab_devices_$i)" 2>/dev/null)"
		if [ -n "${device_name}" ] ; then
			/sbin/cryptsetup -y --key-file "/root/$(eval echo \$luks_decrypted_mtab_key_files_$i)" luksOpen "${device_name}" "$(eval echo \$luks_decrypted_mtab_names_$i)"
		fi
	done

	return 0
}

hook_shutdown_luks_decrypted() {
	helper_luks_read_mtab "${luks_decrypted_config_file}"

	for i in $(seq 0 $(expr ${luks_decrypted_mtab_items_count} - 1)) ; do
		/sbin/cryptsetup luksClose "$(eval echo \$luks_decrypted_mtab_names_$i)"
	done
}

luks_decrypted_config_file=
