#!/bin/sh
#
# Copyright (C) 2023 i.Dark_Templar <darktemplar@dark-templar-archives.net>
#
# This file is part of DT init scripts.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

helper_module_read_config() {
	local MODULE_LIST=$1

	let module_items_count=0

	if [ ! -z "$MODULE_LIST" ]; then
		while read -r line ; do
			set -- $(echo $line | sed -e 's:#.*$::')

			if [ ! -z "$1" ]; then
				eval module_name_${module_items_count}="$1"
				module_items_count=$(expr ${module_items_count} + 1)
			fi
		done < $MODULE_LIST
	fi
}

# parameters: $1 - hook-specific options
hook_parse_args_module() {
	local params=$1

	for param in $(echo $params | sed -e 's|:| |g') ; do
		case $param in
			configfile=*)
				module_config_file=${param#configfile=}
				;;
			# TODO: Notify about unsupported option?
		esac
	done
}

hook_run_module() {
	helper_module_read_config "${module_config_file}"

	for i in $(seq 0 $(expr ${module_items_count} - 1)) ; do
		/sbin/modprobe "$(eval echo \$module_name_$i)"
	done

	return 0
}

module_config_file=
